// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNSvat6JMWGg5uLcSSFSV9c9efAbSdAlY',
    appId: '1:686610092944:web:a5e506c6bcfa1acbb7d915',
    messagingSenderId: '686610092944',
    projectId: 'mor-panchayat',
    authDomain: 'mor-panchayat.firebaseapp.com',
    storageBucket: 'mor-panchayat.firebasestorage.app',
    measurementId: 'G-964GLLBMRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-bCo30yTAJPDXMCdsxomE1FNn6gyTeg',
    appId: '1:686610092944:android:1e7d15d6d0bdca0eb7d915',
    messagingSenderId: '686610092944',
    projectId: 'mor-panchayat',
    storageBucket: 'mor-panchayat.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNSvat6JMWGg5uLcSSFSV9c9efAbSdAlY',
    appId: '1:686610092944:web:ed0b237b45c67522b7d915',
    messagingSenderId: '686610092944',
    projectId: 'mor-panchayat',
    authDomain: 'mor-panchayat.firebaseapp.com',
    storageBucket: 'mor-panchayat.firebasestorage.app',
    measurementId: 'G-8Q8KG2453J',
  );
}
